### ISSUE TITLE
Compile error (execa.ExecaReturns)

### ISSUE THREAD

**Issue by mikaelengstrom** [nuxt/lmify#48]
Hi, so i get this build-error in my application using lmify:

`node_modules/lmify/types/lmify.d.ts:18:54 - error TS2694: Namespace 'execa' has no exported member 'ExecaReturns'.`

Inspecting the execa-library it does indeed not export "ExecaReturns". Changing types/lmify.d.ts to "execa.ReturnValue" resolves the issue, however I do not have the insights in this library or execa to know wheter that is the correct fix for the issue.

**Comment by pi0** [comment]
This project is being deprecated. I suggest you try [unjs/nypm](https://github.com/unjs/nypm) instead.
